open: {id:"aliexpress-shop-url",name:"速卖通整店铺链接",link:"input",timeout:15,threads:1,brower:"chrome",remark:"https://baseus.aliexpress.com/store/group/Wireless-charger/2343184_511590492.html?spm=2114.12010612.0.0.3d3a75509kAjWS"}
  page:{xpath:"//a[@class='ui-pagination-next']"}
    list: {xpath:"//a[@class='pic-rind' or @class='page-next ui-pagination-next']",wait:3000}
      text: {xpath:"",attribute:"href", name:"链接"}
